version: "3"

tasks:
  default:
    cmds:
      - task -l
    silent: true

  run:
    cmds:
      - go install
      - cat secret.yaml | lsd
      - cat secrets.yaml | lsd

  test:
    cmds:
      - go mod tidy
      - golangci-lint run --fix ./...
      - go test -v -race ./...

  cover:
    desc: Show test coverage
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - rm coverage.out
      - xdg-open coverage.html
